PAPP-34334 - add bytes-like object handlin on-prem
splunk-soar-connectors/microsoftexchangeonpremews pull request #38
Opened 2024-07-30 07:57 UTC by mctonderski-splunk

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2024-08-12 11:20 UTC, mposluszny-splunk requested changes

2024-08-12 11:20 UTC, mposluszny-splunk commented on ewsonprem_connector.py
> +        output_str = None
We don't need variable, we can just return None/UnicodeDammi(...)

2024-08-12 11:20 UTC, mposluszny-splunk commented on ewsonprem_connector.py
> +                self.debug_print(f"Error: error occurred while converting to string with detected encoding: {charset=}.")
I'd export 164-173 to separate method, It looks a bit busy with this amount of scopes.

2024-08-12 11:20 UTC, mposluszny-splunk commented on ewsonprem_connector.py
> +        except Exception as e:
Don't we have nay specific exception for decoding error?

2024-08-12 11:20 UTC, mposluszny-splunk commented on ewsonprem_connector.py
> +            try:
We are missing `unreleased.md` changelog update for this fix

2024-08-14 13:04 UTC, ivellios submitted a review, later dismissed
Left comments. Otherwise, all good! 👍🏻

2024-08-14 13:08 UTC, mctonderski-splunk commented on ewsonprem_connector.py
> +            if input_str:
well since it wasn't checked in prev version I think that this aspect should remain the same

2024-08-14 13:11 UTC, ivellios commented on ewsonprem_connector.py
> +            if input_str:
I will rephrase: can input string be `None` or `""`? 
Because for `""` it will return `None` and may result in errors.

2024-08-14 13:11 UTC, ivellios approved these changes

2024-08-14 13:15 UTC, mctonderski-splunk commented on ewsonprem_connector.py
> +            if input_str:
input_str if "" or None should skip it either way

2024-08-14 13:26 UTC, bbielinski-splunk commented on ewsonprem.json
> +            {
Some time ago, the new `dev-cicd-tools` pre-commit hook was released (v1.18), which clears a lot of unneeded wheel files. It's really great and it reduces the amount of work needed, when fixing security vulnerabilities. Could you please bump this hook for this connector and run it?

2024-08-14 13:33 UTC, bbielinski-splunk reviewed
Left some comments, apart from that looks good.

2024-08-14 13:33 UTC, bbielinski-splunk commented on ewsonprem_connector.py
> +    def _handle_different_encodig(self, input_str, charset):
Probably a typo
```suggestion
    def _handle_different_encoding(self, input_str, charset):
```

2024-08-14 13:33 UTC, bbielinski-splunk commented on ewsonprem_connector.py
> +            self.debug_print(f"Warning: error occurred while converting to string with given encoding: {charset=}: {e}.")
What is "=" used for in `{charset=}`

2024-08-14 13:42 UTC, mctonderski-splunk commented on ewsonprem_connector.py
> +            self.debug_print(f"Warning: error occurred while converting to string with given encoding: {charset=}: {e}.")
when used like this it prints both variable name and value

2024-08-14 13:44 UTC, bbielinski-splunk commented on ewsonprem_connector.py
> +            self.debug_print(f"Warning: error occurred while converting to string with given encoding: {charset=}: {e}.")
Nice, I haven't come across this before

2024-08-14 13:45 UTC, bbielinski-splunk approved these changes

2024-08-14 14:20 UTC, ivellios approved these changes

2024-09-23 18:04 UTC, merged